repos:
  - repo: https://github.com/fastai/nbdev
    rev: 2.2.10
    hooks:
      - id: nbdev_clean
      - id: nbdev_export

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2 # Ruff version.
    hooks:
      - id: ruff-check
        types_or: [python, jupyter]
        args: [ --fix ]
      - id: ruff-format
        types_or: [python, jupyter]

