# AUTOGENERATED! DO NOT EDIT! File to edit: 99_example.ipynb.

# %% auto 0
__all__ = []

# %% 99_example.ipynb 2
from datetime import datetime

import streamlit as st

from streamlit_jupyter import StreamlitPatcher, tqdm

# %% 99_example.ipynb 4
st.title("Example")

# %% 99_example.ipynb 5
st.markdown(
    """

This is a test page demonstrating the use of `streamlit_jupyter`.

If you're seeing this in jupyter, then it's working!

"""
)

# %% 99_example.ipynb 7
name = st.text_input("What's your name?", "John")

# %% 99_example.ipynb 8
date = st.date_input("Choose a date", datetime.now().date())

# %% 99_example.ipynb 9
st.markdown(f"## Hello {name}!\n## The date is {date.strftime('%Y-%m-%d')}")

# %% 99_example.ipynb 11
import time
import pandas as pd


@st.cache(suppress_st_warning=True)
def get_data(date):
    for i in tqdm(range(20)):
        time.sleep(0.1)
    return pd.DataFrame(
        {"date": pd.date_range(date, periods=3), "c": [7, 8, 5], "d": [10, 11, 3]}
    ).set_index("date")


df = get_data(date)
st.write(df)

# %% 99_example.ipynb 14
import plotly.express as px

df_daily = df.mean(axis="columns").rename("daily_average")
fig = px.line(df_daily, title="Daily mean", width=600)
st.write(fig)

# %% 99_example.ipynb 15
st.code("print(1+1)", language="python")

# %% 99_example.ipynb 16
show_code = st.checkbox("Show code", value=True)

# %% 99_example.ipynb 17
if show_code:
    st.code("[i**2 for i in range(100)]")

# %% 99_example.ipynb 18
option = st.radio("Choose one option", options=["foo", "bar"], index=1)

# %% 99_example.ipynb 19
option = st.selectbox("Selectbox: ", options=["Jane", "Bob", "Alice"], index=0)

# %% 99_example.ipynb 20
options = st.multiselect("Multiselect: ", options=["python", "golang", "julia", "rust"])

# %% 99_example.ipynb 21
options = st.multiselect(
    "Multiselect with defaults: ",
    options=["nbdev", "streamlit", "jupyter", "fastcore"],
    default=["jupyter", "streamlit"],
)
