# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/streamlit-jupyter',
                'doc_host': 'https://ddobrinskiy.github.io',
                'git_url': 'https://github.com/ddobrinskiy/streamlit-jupyter',
                'lib_path': 'streamlit_jupyter'},
  'syms': { 'streamlit_jupyter.core': { 'streamlit_jupyter.core.StreamlitPatcher': ( 'core.html#streamlitpatcher',
                                                                                     'streamlit_jupyter/core.py'),
                                        'streamlit_jupyter.core.StreamlitPatcher.__init__': ( 'core.html#streamlitpatcher.__init__',
                                                                                              'streamlit_jupyter/core.py'),
                                        'streamlit_jupyter.core.StreamlitPatcher._get_streamlit_methods': ( 'core.html#streamlitpatcher._get_streamlit_methods',
                                                                                                            'streamlit_jupyter/core.py'),
                                        'streamlit_jupyter.core.StreamlitPatcher.echo': ( 'core.html#streamlitpatcher.echo',
                                                                                          'streamlit_jupyter/core.py'),
                                        'streamlit_jupyter.core.StreamlitPatcher.methods': ( 'core.html#streamlitpatcher.methods',
                                                                                             'streamlit_jupyter/core.py'),
                                        'streamlit_jupyter.core.StreamlitPatcher.patch': ( 'core.html#streamlitpatcher.patch',
                                                                                           'streamlit_jupyter/core.py')}}}
